7 post/api/reviews/review id/comments
kontsio1/NC-games-project pull request #7
Opened 2022-12-13 16:21 UTC by kontsio1

2022-12-13 16:54 UTC, Dutton1990 commented on __tests__/app.test.js
> +  test("status:200, responds with the posted comment object", () => {
wrong status in description

2022-12-13 16:54 UTC, Dutton1990 commented on controllers/controller.js
> +  console.log(author, review_id, body)
dont forget to remove console logs!

2022-12-13 16:56 UTC, Dutton1990 commented on __tests__/app.test.js
> +  })
this would be a 404 because the username could not be found, rather than a 400 bad request

2022-12-13 16:58 UTC, Dutton1990 requested changes
Hey Konstantinos, a few suggested changes above 😄 

Another test you can do is for review/banana/comments for example, this should be a 400! 

Once you've made those changes send it over to us again tomorrow please!

2022-12-14 09:53 UTC, lewispricey approved these changes
Great testing updates! really thorough in testing every possibility of a bad user input.

Good to merge 🚀

2022-12-14 09:53 UTC, lewispricey commented on models/model.js
> +  return db.query(`INSERT INTO comments (author, review_id, body) VALUES ($1, $2, $3) RETURNING *`, [author, review_id, body]).then((data)=>{
Nice use of parameterization to prevent SQL injection!

2022-12-14 10:26 UTC, merged