finished 8-patch
kontsio1/NC-games-project pull request #8
Opened 2022-12-14 12:20 UTC by kontsio1

2022-12-14 12:39 UTC, lewispricey requested changes
Great work on this endpoint so far!

Please can you add some testing for if the ID passed in is the wrong type "/.../review/banana" and a test for if the ID is valid but doesn't exist in the database.

Please raise another PR (tomorrow now) once thats been updated.

2022-12-14 12:39 UTC, lewispricey commented on __tests__/app.test.js
> +    const patchedVotes = {inc_votes: "It's snowing!"};
Love this test assertion 😆

2022-12-14 12:39 UTC, lewispricey commented on errors/error-handlers.js
> +    if (err.code === "22P02" || err.code === '23502') {
Great way to handle this error without having an extra if statement as this uses the same error message 👍

2022-12-14 12:39 UTC, lewispricey commented on controllers/controller.js
> +    res.status(200).send({review})
Great choice of key to send the data back on.

2022-12-14 12:39 UTC, lewispricey commented on models/model.js
> +  if (Object.keys(patchObject).length === 1) {
Rarther than key length, it would be better to check there's a value on the explicit key you're looking for.

2022-12-15 09:58 UTC, Dutton1990 commented on models/model.js
> +  if (Object.keys(patchObject).length === 1) {
Yes I would just ignore any unnecessary keys as you have control over the query. I guess with this solution someone could just send over {bestProgrammerAround: 'me'} and it would get into this block! 

You are free to change this yourself without sending another PR 😄

2022-12-15 09:58 UTC, Dutton1990 commented
Thanks for adding that extra test! You can merge this branch when you're ready. Nice job!

2022-12-15 10:19 UTC, merged